name: update-shells-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 9 1 * *'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
      - name: Install Nix
        uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v19
        with:
          pr-title: "Update shells flake.lock"
          path-to-flake-dir: 'shells/'
          pr-labels: |
            dependencies
            automated
